name: iac-ci

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ci_stage_apply:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.0.0
      - name: Checkout terraform packager
        uses: actions/checkout@v3.0.0
        with:
          repository: smsilva/terraform-packager
          ref: 0.4.3
          path: terraform-packager
      - name: Checkout IAC Code
        uses: actions/checkout@v3.0.0
        with:
          repository: estevaofay/iac-aws-vpc
          path: iac-aws-vpc
      - name: Build Image
        run: |
          ls
          ls $GITHUB_WORKSPACE

