name: iac-ci

on:
  workflow_dispatch:

jobs:
  ci_stage_apply:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: checkout terraform packager
        uses: terraform-packager/checkout@0.4.3

